### ISSUE TITLE
Amazon Location ServiceとMapLibre GL JSとAWS AmplifyとVue.jsを組み合わせてマップアプリケーションを構築してみた

### ISSUE THREAD

**Issue by dayjournal** [aws-amplify-jp/amplify-meetup-cfp#12]
## 発表概要
Amazon Location ServiceとMapLibre GL JSとAWS AmplifyとVue.jsを組み合わせて、マップアプリケーションを構築しましたので、その内容を紹介できればと思います。

https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/js
https://aws.amazon.com/jp/location

### お名前(ハンドルネーム可)
Yasunori Kirimoto

### 所属
[MIERUNE Inc.](https://mierune.co.jp) / [dayjournal](https://day-journal.com)

### 自己紹介
位置情報分野のMIERUNEという会社で組織マネジメントしたり、dayjournalという個人屋号で活動してたりします。

### Twitter ID (連絡用)
@dayjournal_nori

**Comment by watilde** [comment]
Closing as done. Thank you!
