### ISSUE TITLE
Amplifyでいろんな機能拡張をしていったお話

### ISSUE THREAD

**Issue by taka-guevara** [aws-amplify-jp/amplify-meetup-cfp#13]
## 発表概要
１年ほど前にAmplifyでリリースしたサービスを、この１年間でいろんな機能を実装していったお話をします
ベストプラクティスではありませんが、一つの事例としてお話しできればと思っています。

* AuthenticationとAdmin Queries APIによる利用企業様アカウント管理
* APIの@Authによる個人情報の閲覧制限
* Storageによるファイル共有とファイルへのアクセスとその制限

### お名前(ハンドルネーム可)
髙田健太郎(ゲバラ)

### 所属
株式会社POL

### 自己紹介
フロント、バック、インフラ色々いじっています。最近はスクレピング始めました。

### Twitter ID (連絡用)
[@POL53297840](https://twitter.com/POL53297840)

## 補足情報
弊社の採用募集もさせていただければ幸いです。

**Comment by watilde** [comment]
Closing as done. Thank you!
