### ISSUE TITLE
React Native + Amplifyで新規事業のアプリを開発している話

### ISSUE THREAD

**Issue by YujiAdachi** [aws-amplify-jp/amplify-meetup-cfp#17]
## 発表概要

React Native + Amplifyで新規事業のアプリを開発している話がしたいです！
開発初期のフェーズから現在に至るまで、様々なAmplifyに関連する技術的負債がありました。
セッションでは、これまでの技術的負債の戦いについて触れていきます。

### お名前(ハンドルネーム可)

足立 優司

### 所属

[メック株式会社](https://www.mec-co.com/)

### 自己紹介

はじめまして！

私は、[オトとりっぷ](https://www.oto-trip.com/)という犬用音楽アプリを開発しています。
電子基板向け薬品を製造する化学メーカーの新規事業として、React Native + Amplifyで開発しています。

### Twitter ID (連絡用)

adt0705

## 補足情報
//その他発表内容、登壇者情報について補足があればご記入ください

**Comment by ikenyal** [comment]
https://aws-amplify-jp.connpass.com/event/273121/
にて登壇いただきました
