### ISSUE TITLE
Amplify をフルスタック以外にも柔軟に使う方法

### ISSUE THREAD

**Issue by coa00** [aws-amplify-jp/amplify-meetup-cfp#18]
## 発表概要
Amplify の monorepo 運用による複数プロジェクト開発

登壇者情報
お名前
coa00 ( 青木光平）

所属
株式会社 Purpom Media Lab(ピュアポムメディアラボ）
https://purpom-media-lab.com/

自己紹介
MVP開発を研究・提供を行うラボを運営しています。
高速に技術スタックとして、Amplify を採用し、日々研究を行なっております。

**Comment by ikenyal** [comment]
https://aws-amplify-jp.connpass.com/event/273121/
にて登壇いただきました
