### ISSUE TITLE
Amplify によるWeb&ネイティブアプリ開発とチーム運営

### ISSUE THREAD

**Issue by coa00** [aws-amplify-jp/amplify-meetup-cfp#2]
## 発表概要
Amplify によるWeb&ネイティブアプリ開発とチーム運営 

- Amplify の特性を生かしてこんなサービスつくってきました！
- Amplify x Expo をつかって Web と アプリを自動ビルド！
- Amplify をよりはやく正確に工数をおさえて開発するためのライブラリ！

### お名前(ハンドルネーム可)
coa00 (青木光平）

### 所属
O: 株式会社

### 自己紹介

プログラマー、ディレクション、UX デザインまでなんでもやります。
現在は、O: のCTOをやっています。

## 補足情報
//その他発表内容、登壇者情報について補足があればご記入ください

**Comment by jaga810** [comment]
こんにちは！Amplify Meetup運営のじゃがと申します。
この度はAmplify Meetup #03にご応募いただきありがとうございました！
本日運営で会議を行い、ぜひ @coa00  さんに登壇いただきたいと考えております。

つきましては3/12(金)までに

* 登壇可否
* 登壇可能な場合、連絡先メールアドレス

の2点を私のTwitter DM([@jagaimogmog](https://twitter.com/jagaimogmog))、またはメール(daisnaga@amazon.co.jp)まで教えていただけますと幸いです。
ご確認のほど、よろしくお願いいたします！

**Comment by jaga810** [comment]
登壇意志の確認と連絡先の共有を実施したため、こちらCloseさせていただきます！
