### ISSUE TITLE
Amplify OSSプロジェクトにコントリビュートしてAmplify Badgeを手に入れよう！

### ISSUE THREAD

**Issue by fossamagna** [aws-amplify-jp/amplify-meetup-cfp#20]
## 発表概要
Amplify Badge Programの紹介とAmplify OSSプロジェクトにコントリビュートしていくにはどう始めるといいかについてお話しします。

### お名前(ハンドルネーム可)
村上雅彦(fossamagna)

### 所属
株式会社永和システムマネジメント

### 自己紹介
アプリケーションからインフラまでなんでもやるエンジニアとしてお仕事してます。
[amplify-cli](https://github.com/aws-amplify/amplify-cli) を中心にAmplify関連のリポジトリにコントリビューションするのが趣味で、JavaScript/TypeScriptを使うことが多いですが、最近はFlutterを触っている時間も増えました。

### Twitter ID (連絡用)
fossamagna

## 補足情報
//その他発表内容、登壇者情報について補足があればご記入ください

**Comment by ikenyal** [comment]
Amplify Boost Up #03 にて採択
https://aws-amplify-jp.connpass.com/event/284533/
