### ISSUE TITLE
Amplify × ブロックチェーン で取引管理システムを作った話

### ISSUE THREAD

**Issue by kita3222** [aws-amplify-jp/amplify-meetup-cfp#21]
## 発表概要
Amplifyとブロックチェーンを組み合わせて、取引管理システムを作ったのでそちらについて発表します。

## 登壇者情報
北見 海貴

### 所属
株式会社 Purpom Media Lab
Amplify User Group Japan 運営

### 自己紹介
株式会社 Purpom Media Labでエンジニアをしております。
サーバレスを使った開発が好きです。

### Twitter ID (連絡用)
https://twitter.com/kita3222

## 補足情報
特になし

**Comment by ikenyal** [comment]
Amplify Boost Up #03 にて採択
https://aws-amplify-jp.connpass.com/event/284533/
