### ISSUE TITLE
本番環境でAmplifyを3年くらい使ってみている弊社環境のご紹介

### ISSUE THREAD

**Issue by miura-bd** [aws-amplify-jp/amplify-meetup-cfp#23]
## 発表概要
//記入例は[こちら](https://github.com/aws-amplify-jp/amplify-meetup-3-cfp/issues/1)
//250字以内

我々開発チームでは、動画配信サービスとECサービスの2つを運用開発しています。フルスクラッチで活用する際に Amplify-CLI でできることを中心に構築を行っています。
Amplify Web Hosting + AppSync をメインとした構成になっているので、その事例をご紹介させていただければと思います
ノリと勢いで機能を増やして行った結果、まずいことになったのも触れます
（なお、Amplify GraphQL Transformer v2 に移行するタイミングを完全に見失った状態です）

### お名前(ハンドルネーム可)
三浦一樹

### 所属
北海道テレビ放送

### 自己紹介
//100字以内
AWS Samurai 2019 | AWS Community Hero
サーバーレスでしか、サービスを構築できない体に。コミュニティが大好きでJAWS-UG札幌支部、MediaJAWSの運営 をしてます

### Twitter ID (連絡用)
@miu_crescent

## 補足情報
//その他発表内容、登壇者情報について補足があればご記入ください

**Comment by ikenyal** [comment]
`Amplify Boost Up #4` にて採択
https://aws-amplify-jp.connpass.com/event/300944/
