### ISSUE TITLE
サービス立ち上げから運用で感じたAWS Amplifyの開発者体験を紹介

### ISSUE THREAD

**Issue by dyson-yamashita** [aws-amplify-jp/amplify-meetup-cfp#24]
## 発表概要
AWS Amplifyを使ってプロジェクトマネジメント向けサービスを立ち上げ、約3年間運営しています。
サービス立ち上げから運用をしていく中で感じたAWS Amplifyにおける開発者体験について紹介していきます。また、開発者体験におけるAWS Amplifyの正体について語ります。

### お名前(ハンドルネーム可)
山下　義陽

### 所属
NTTスマートコネクト

### 自己紹介
Vue.js + Amplifyでのフロント開発しています。
会社員をするかわたら、PM向けサービスを立ち上げました。

### Twitter ID (連絡用)
@udonsin

**Comment by ikenyal** [comment]
`Amplify Boost Up #4` にて採択
https://aws-amplify-jp.connpass.com/event/300944/
