### ISSUE TITLE
CodeCatalystで始める最速(!?)のアプリ開発

### ISSUE THREAD

**Issue by kenta773** [aws-amplify-jp/amplify-meetup-cfp#26]
## 発表概要
CodeCatalystを使えばAmplifyを使ったサンプルアプリをCI/CD付きで爆速デプロイできます！
まだAmplifyを使ったことない方、使おうとして挫折してしまった方に、まずは完成系から自分色に染めていきませんかという提案をさせていただきます。

## 希望発表時間(質疑応答時間は別途設けるので、登壇時間の希望を記載)
登壇 10分

## 登壇形式
現地

### お名前(ハンドルネーム可)
水村健太

### 所属
株式会社大和総研

### 自己紹介
応募時点で社会人4年目の水村と申します。
2023年度のAWS Jr.Championsとして活動してまいりました。兼ねてより推しサービスであるCodeCatalystをテーマに複数LT登壇しております。
以前Boost upに参加した際のレベルが高く場違いかもしれませんがよろしくお願いいたします。

### Discordのアカウント(コミュニティのDiscord内で、登壇者を招待したプライベートチャンネルでやりとりを実施)
kenta6643
※コミュニティには参加しております

## 補足情報
デモを交えるかパワポのみかすら決まっておりません。。

**Comment by ikenyal** [comment]
`Amplify Boost Up #5` にて採択
https://aws-amplify-jp.connpass.com/event/312975/
