### ISSUE TITLE
Amplifyで開発・運用している個人開発アプリ紹介

### ISSUE THREAD

**Issue by tttol** [aws-amplify-jp/amplify-meetup-cfp#27]
## 発表概要
自分用の簡単な家計管理アプリを開発し、そのアプリをAmplifyで運用しています。
なぜAmplifyを採用したのか、アプリの概要、Amplifyで開発運用してみてどうだったかについて話します。

## 希望発表時間(質疑応答時間は別途設けるので、登壇時間の希望を記載)
登壇 15分

## 登壇形式
現地

### お名前(ハンドルネーム可)
髙橋透

### 所属
NRIネットコム株式会社

### 自己紹介
NRIネットコム株式会社でWebアプリエンジニアをしています。
先日AWS Community Builderに選抜されました。
よろしくお願いします。

## 補足情報
//その他発表内容、登壇者情報について補足があればご記入ください
過去の登壇歴は[こちら](https://github.com/tttol)

**Comment by ikenyal** [comment]
`Amplify Boost Up #5` にて採択
https://aws-amplify-jp.connpass.com/event/312975/
