### ISSUE TITLE
生成AIを使ってAmplify Gen2を楽しく学べるワークショップをやってみた

### ISSUE THREAD

**Issue by mkdev10** [aws-amplify-jp/amplify-meetup-cfp#29]
## 発表概要
AmplifyとBedrockのWorkshop「Learning Plan Generator with AWS Amplify」の紹介。
Gen2の手軽さとBedrockとの連携が学べる良いワークショップだったので内容の共有したい。
ワークショップのアプリをカスタマイズした話などを盛り込みたい。

## 希望発表時間(質疑応答時間は別途設けるので、登壇時間の希望を記載)
登壇 10分

## 登壇形式
現地

## 登壇者情報
桒原 政睦

### 所属
大阪シーリング印刷

### 自己紹介
大阪の老舗製造業で内製システム開発に従事。AmplifyをきっかけにAWSにどハマりし、社内でAWS導入を推進。今年の目標はOSSにコントリビュートすること。

### Discordのアカウント(コミュニティのDiscord内で、登壇者を招待したプライベートチャンネルでやりとりを実施)
k.masachika(mkdev10)

**Comment by ikenyal** [comment]
06で登壇
