### ISSUE TITLE
レガシーなWebシステムにAmplifyを生やしてみた話

### ISSUE THREAD

**Issue by me-minamijima** [aws-amplify-jp/amplify-meetup-cfp#3]
## 発表概要
弊社で運営しているPHPで構築されたレガシーなWEBシステムに、Amplifyで構築した新たなシステムを緩く結合しました。

- Amplify選定の経緯
- はじめてのスクラム開発
- 既存のサイトからSSO(シングルサインオン)でログインさせなくちゃいけなかった話
- GraphQL+距離検索を導入した時の話

## 登壇者情報
1. 南島 康一
2. 向 宇

### 所属
株式会社マーケットエンタープライズ

### 自己紹介
マーケットエンタープライズという会社でテックリードをやらせていただいております。
システムの設計とバックエンドの開発を主に担当していて、技術選定にも深く関わっています。
なるべくシンプルに構築するのが好きで、サーバーレスやAmplifyなどは大好物です。
次はGolangを導入しようと目論んでいて、AmplifyにGoのLambdaを生やすチャンスを伺っています。

それと、トライリンガルなフロントエンドエンジニアの向からも少しお話させてください。

## 補足情報
システムに導入されている技術はこんな感じです。
Vue/TypeScript/GraphQL(AppSync)/DynamoDB/ElasticSearch/Cognito
(連携部分: Lambda(python)/RDS+Trigger/S3)

**Comment by jaga810** [comment]
こんにちは！Amplify Meetup運営のじゃがと申します。
この度はAmplify Meetup #03にご応募いただきありがとうございました！
本日運営で会議を行い、ぜひ @me-minamijima  さんに登壇いただきたいと考えております。

つきましては3/12(金)までに

* 登壇可否
* 登壇可能な場合、連絡先メールアドレス

の2点を私のTwitter DM([@jagaimogmog](https://twitter.com/jagaimogmog))、またはメール(daisnaga@amazon.co.jp)まで教えていただけますと幸いです。
ご確認のほど、よろしくお願いいたします！

**Comment by jaga810** [comment]
登壇意志の確認と連絡先の共有を実施したため、こちらCloseさせていただきます！

**Comment by jaga810** [comment]
登壇意志の確認と連絡先の共有を実施したため、こちらCloseさせていただきます！
