### ISSUE TITLE
AmplifyGen2+Nxで構築するNext.jsモノレポ構成

### ISSUE THREAD

**Issue by mah77ss** [aws-amplify-jp/amplify-meetup-cfp#30]
## 発表概要

AmplifyGen2のmonorepo構成を使って、フロントとバックエンドを分けたNext.jsアプリの構築経験をシェア。
Qiitaに投稿した内容をブラッシュアップし、スライドにまとめて発表します。

https://qiita.com/mamoru-ssoft/items/816de5cc084c6f739fe7

## 希望発表時間(質疑応答時間は別途設けるので、登壇時間の希望を記載)
登壇 10分

## 登壇形式
オンライン

## 登壇者情報
ま〜(一瀬 護)

### 所属
デザインカロン合同会社

### 自己紹介
約3年前からフロントアプリの開発に従事。
AmplifyGen1より色々使いやすくなっている所があるので、ウェブアプリの爆速開発を推進していきたい。

### Discordのアカウント(コミュニティのDiscord内で、登壇者を招待したプライベートチャンネルでやりとりを実施)
mah771(Mah)

**Comment by ikenyal** [comment]
06で登壇
