### ISSUE TITLE
Amplifyで作る配信サイト/ビデオチャットWebアプリ

### ISSUE THREAD

**Issue by matsuihidetoshi** [aws-amplify-jp/amplify-meetup-cfp#5]
## 発表概要
**AWS Amplify** と **Amazon IVS** や **Amazon Chime** などのメディア系サービスを組み合わせてこんなサービスを作ったよ！
- JAWS DAYS 2021 - re:Connect 配信サイト
- ビデオチャットWebアプリ

## 登壇者情報
松井英俊

### 所属
株式会社スタートアップテクノロジー

### 自己紹介
普段はRailsやVue.js/Nuxt.jsを使ったWeb開発に携わっています。お気に入りはAWS Amplify。

## 補足情報
//その他発表内容、登壇者情報について補足があればご記入ください

**Comment by jaga810** [comment]
こんにちは！Amplify Meetup運営のじゃがと申します。
この度はAmplify Meetup #03にご応募いただきありがとうございました！
本日運営で会議を行い、ぜひ @matsuihidetoshi  さんに登壇いただきたいと考えております。

つきましては3/12(金)までに

* 登壇可否
* 登壇可能な場合、連絡先メールアドレス

の2点を私のTwitter DM([@jagaimogmog](https://twitter.com/jagaimogmog))、またはメール(daisnaga@amazon.co.jp)まで教えていただけますと幸いです。
ご確認のほど、よろしくお願いいたします！

**Comment by matsuihidetoshi** [comment]
@jaga810 
こんばんは！
この度は登壇のオファーをいただきありがとうございます！
喜んで登壇させていただきたく存じます！

後ほどTwitterにてご連絡いたします！

**Comment by jaga810** [comment]
登壇意志の確認と連絡先の共有を実施したため、こちらCloseさせていただきます！
