### ISSUE TITLE
toCサービスをAWS Amplify使って構築、運用しているお話

### ISSUE THREAD

**Issue by tani1987** [aws-amplify-jp/amplify-meetup-cfp#6]
## 発表概要
ReactNative - Cognito認証で運用していたアプリをAWS Amplify ConsoleでWebに載せ替えました！
toCサービスを商用環境で運営 / 随時改善してます。
また、Pinpointも導入しユーザーのアクティビティ等も分析しています。

- お世話になった機能 
  - CI / CD
  - Pinpoint
  - カスタムドメイン設定
  - パスワードの保護

### お名前(ハンドルネーム可)
ﾗﾗﾀﾝ!!肉屋のCTO(谷 耕平)

### 所属
株式会社ビータス 所属

### 自己紹介
ミート矢澤を経営している企業にてCTOしてます。
新卒でワークスアプリケーションズで開発者になり、
東京で2年働いて上海で1年半働いてました。
その後Web制作会社を起業して3年半後、今の会社に来ました。

## 補足情報
toCサービスの商用環境でどのようにAmplifyを利用しているかの参考になればと思います。

**Comment by jaga810** [comment]
こんにちは！Amplify Meetup運営のじゃがと申します。
この度はAmplify Meetup #03にご応募いただきありがとうございました！
本日運営で会議を行い、ぜひ @tani1987   さんに登壇いただきたいと考えております。

つきましては3/12(金)までに

* 登壇可否
* 登壇可能な場合、連絡先メールアドレス

の2点を私のTwitter DM([@jagaimogmog](https://twitter.com/jagaimogmog))、またはメール(daisnaga@amazon.co.jp)まで教えていただけますと幸いです。
ご確認のほど、よろしくお願いいたします！

**Comment by jaga810** [comment]
登壇意志の確認と連絡先の共有を実施したため、こちらCloseさせていただきます！
