### ISSUE TITLE
バックエンドエンジニアがAmplifyで中規模案件に挑戦した話

### ISSUE THREAD

**Issue by SCP-kimura** [aws-amplify-jp/amplify-meetup-cfp#7]
## 発表概要
React初心者、AWSもさほど詳しくない人たちが集まり、amplifyを使用して会員制コミュニケーションWebアプリを開発したなかで得た知見を紹介するよ！！

- Amplifyの技術をどう習得したか
- チームでAmplifyを開発して得られた知見
- Amplify×データ設計のお話
- Amplifyの環境作成ではまりどう解決したか
- Amplifyで非機能要件を達成する

### お名前(ハンドルネーム可)
木村宏明

### 所属
株式会社スカラパートナーズ

### 自己紹介
WEBエンジニア、PM、マネージメントを経て、
昨年から、また現場で新規事業立ち上げに携わり、技術研鑽に励んでいます。

## 補足情報
サーバーサイドエンジニアが集まって、試行錯誤しながらAmplifyでSPAを開発しました。
AmplifyのSNS Workshop（boyaki）を行ったあと、１からAmplifyアプリを
どう開発していくかの参考になると思います。

**Comment by jaga810** [comment]
こんにちは！Amplify Meetup運営のじゃがと申します。
この度はAmplify Meetup #03にご応募いただきありがとうございました！
本日運営で会議を行い、ぜひ @SCP-kimura   さんに登壇いただきたいと考えております。

つきましては3/12(金)までに

* 登壇可否
* 登壇可能な場合、連絡先メールアドレス

の2点を私のTwitter DM([@jagaimogmog](https://twitter.com/jagaimogmog))、またはメール(daisnaga@amazon.co.jp)まで教えていただけますと幸いです。
ご確認のほど、よろしくお願いいたします！

**Comment by jaga810** [comment]
登壇意志の確認と連絡先の共有を実施したため、こちらCloseさせていただきます！
